library(RMySQL)
mydb = dbConnect(MySQL(), user='root', password='', dbname='advanced_tech', host='localhost')
dbListTables(mydb)
dbListFields(mydb, 'customer_rating')
rs = dbSendQuery(mydb, "select x, y from customer_rating")
data <- fetch(rs, n=200)
plot.default(data, pch=19, col="green")
par(bg='#2a2a2e')
title(main='Customer Rating')
dbClearResult(rs)
dbDisconnect(mydb)