library(RMySQL)
mydb = dbConnect(MySQL(), user='root', password='', dbname='advanced_tech', host='localhost')
dbListTables(mydb)
dbListFields(mydb, 'mock_product_data')
rs = dbSendQuery(mydb, "select * from mock_product_data")
fetch(rs, n=1000)
dbClearResult(rs)
dbDisconnect(mydb)
