library(RMySQL)
mydb = dbConnect(MySQL(), user='root', password='', dbname='advanced_tech', host='localhost')
dbListTables(mydb)
dbListFields(mydb, 'MOCK_Product_DATA')
rs = dbSendQuery(mydb, "select price, quantity from MOCK_Product_DATA")
data <- fetch(rs, n=1000)
plot.default(data)
dbClearResult(rs)
dbDisconnect(mydb)
